name: Deploy plugins

on:
  push:
    tags:
      - v*

env:
  PATH_TO_AU:  "build/RNBOAudioPlugin_artefacts/Release/AU/lulu.component"
  PATH_TO_VST: "build/RNBOAudioPlugin_artefacts/Release/VST3/lulu.vst3"
  PATH_TO_INSTALLATION_EN: "documentation/installation_en.pdf"
  PATH_TO_INSTALLATION_JA: "documentation/installation_ja.pdf"
  PATH_TO_MANUAL_EN: "documentation/manual_en.pdf"
  PATH_TO_MANUAL_JA: "documentation/manual_ja.pdf"
  PACKAGE_NAME_MAC: "lulu-mac"
  
jobs:
  deploy-osx:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote
    - name: Build
      working-directory: ./build
      run: |
        cmake .. -G Xcode
        cmake --build . --config Release
    - name: Packaging
      run: |
        mkdir ${{ env.PACKAGE_NAME_MAC }}
        cp -r ${{ env.PATH_TO_AU }} ${{ env.PACKAGE_NAME_MAC }}
        cp -r ${{ env.PATH_TO_VST }} ${{ env.PACKAGE_NAME_MAC }}
        cp -r ${{ env.PATH_TO_INSTALLATION_EN }} ${{ env.PACKAGE_NAME_MAC }}
        cp -r ${{ env.PATH_TO_INSTALLATION_JA }} ${{ env.PACKAGE_NAME_MAC }}
        cp -r ${{ env.PATH_TO_MANUAL_EN }} ${{ env.PACKAGE_NAME_MAC }}
        cp -r ${{ env.PATH_TO_MANUAL_JA }} ${{ env.PACKAGE_NAME_MAC }}
        zip -r ${{ env.PACKAGE_NAME_MAC }}.zip ${{ env.PACKAGE_NAME_MAC }}
        rm -r ${{ env.PACKAGE_NAME_MAC }}
    - name: Release
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.PACKAGE_NAME_MAC }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
